# Векторные пространства и NumPy

In [40]:
import numpy
from scipy.spatial.distance import cdist

## 2. Чему равна манхэттенская норма вектора $a = (-1, 2, -1)$?

In [21]:
abs(-1) + abs(2) + abs(-1)

4

$||a||_{L_1} = |-1| + |2| + |-1| = 4 $

## 3. Чему равно скалярное произведение векторов $a=(1, 2, 3)$ и $b=(-3, 1, 1)$?

In [23]:
a = [1, 2, 3]
b = [-3, 1, 1]

In [27]:
sum([x * y for x, y in zip(a, b)])

2

$ \langle a, b \rangle = (1 \cdot -3) + (2 \cdot 1) + (3 \cdot 1) = 2 $

## **5. Какие из нижеприведенных команд корректно отработают и создадут вектор?**

In [10]:
b = numpy.array([1, 2, 3, 4, 5], dtype=float); b # True

array([1., 2., 3., 4., 5.])

In [11]:
f = numpy.arange(1, 2, 0.3, dtype=float); f # True

array([1. , 1.3, 1.6, 1.9])

In [12]:
b = numpy.array(1, 2, 3, 4, 5, dtype=float); b

ValueError: only 2 non-keyword arguments accepted

In [13]:
c = numpy.array([False, False, True]); c # True

array([False, False,  True])

## 6. Пусть даны два вектора `a = numpy.array([6, 3, -5])` и `b = numpy.array([-1, 0, 7])`. Какая из следующих команд считает евклидово расстояние между этими векторами?

In [45]:
a = numpy.array([6, 3, -5])
b = numpy.array([-1, 0, 7])

In [46]:
cdist(b, a, metric='euclidean')

ValueError: XA must be a 2-dimensional array.

In [47]:
numpy.linalg.norm(a, ord=2) - numpy.linalg.norm(b, ord=2)

1.2955324534752801

In [49]:
cdist(a[:, numpy.newaxis], b[:, numpy.newaxis], metric='euclidean')

array([[ 7.,  6.,  1.],
       [ 4.,  3.,  4.],
       [ 4.,  5., 12.]])

In [50]:
cdist(a[numpy.newaxis, :], b[numpy.newaxis, :], metric='euclidean') # True

array([[14.2126704]])

## 7. Пусть даны два вектора `a = numpy.array([0, -1, 11])` и `b = numpy.array([3, 7, 2])`. Какие из следующих команд считают скалярное произведение этих векторов?

In [51]:
a = numpy.array([0, -1, 11])
b = numpy.array([3, 7, 2])

In [52]:
numpy.dot(a, b) # True

15

In [53]:
b.dot(a) # True

15

In [56]:
a * b

array([ 0, -7, 22])

In [57]:
numpy.dot(a, b) / numpy.linalg.norm(a) / numpy.linalg.norm(b)

0.1724707686818527

## **8. Пусть дан вектор `a = numpy.array([8, 10, -1, 0, 0])`. Какие из следующих команд преобразуют вектор a к вектор-столбцу?**

In [14]:
a = numpy.array([8, 10, -1, 0, 0])

In [15]:
a.reshape((1, 5))

array([[ 8, 10, -1,  0,  0]])

In [16]:
a.reshape((5, 1)) # True

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [17]:
a[:, numpy.newaxis] # True

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [18]:
a[numpy.newaxis, :]

array([[ 8, 10, -1,  0,  0]])